//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT06
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<double> GPA { get; set; }
        public Nullable<bool> Picture { get; set; }
        public Nullable<bool> School_report { get; set; }
        public Nullable<bool> CCCD { get; set; }
    }
}
